apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: requestHeadersIdP
    type: RequestHeader
    requestHeader:
      ca:
        name: request-header-ca
      headers: ["X-Remote-User"]
      loginURL: "https://${PROXY_ROUTE}/web-login/oauth/authorize?${query}"
      challengeURL: "https://${PROXY_ROUTE}/challenges/oauth/authorize?${query}"

